name = "bima-akbar-dev"
main = "dist/_worker.js"
compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
observability = { enabled = true }

[build]
command = "npx astro build"

[[kv_namespaces]]
binding = "BIMA_KV_SPACE"
id = "30c729861a2b4e21b15c8ce0f5539e75"

[vars]
VITE_BLOGGER_API_KEY = "AIzaSyAF5IX_benL0vfFXYas3BYQrenGpbl4hek"
VITE_BLOGGER_BLOG_ID = "5920132421647282747"
