# public/admin/config.yml

backend:
name: git-gateway
branch: main

display_url: https://bimaakbar.my.id
publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    editor:
      preview: false

    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "text", required: true, hint: "Deskripsi singkat untuk SEO dan Ringkasan Postingan. Max 160 karakter."}
      - {label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true, hint: "Tanggal publikasi postingan."}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false, allow_multiple: false, choose_url: false, media_library: { config: { multiple: false } }, hint: "Gambar utama untuk postingan blog. Disarankan format WebP/AVIF."}
      - {label: "Author", name: "author", widget: "string", required: false, default: "Bideon", hint: "Nama penulis postingan."}
      - {label: "Category", name: "category", widget: "string", required: false, hint: "Kategori postingan (contoh: Web Development, Desain, Tutorial)."}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag Name", name: "tag", widget: "string"}, required: false, hint: "Daftar tag terkait postingan."}
      - {label: "Is Featured?", name: "isFeatured", widget: "boolean", default: false, hint: "Centang jika postingan ini ingin ditampilkan sebagai 'Featured Post'."}
      

      - label: "SEO / Open Graph Settings"
        name: "seo_og_settings"
        widget: "object"
        collapsed: true
        fields:
          - {label: "OG Title", name: "ogTitle", widget: "string", required: false, hint: "Opsional: Ganti judul untuk share di media sosial (Open Graph Title)."}
          - {label: "OG Description", name: "ogDescription", widget: "text", required: false, hint: "Opsional: Ganti deskripsi untuk share di media sosial (Open Graph Description)."}
          - {label: "OG Image", name: "ogImage", widget: "image", required: false, allow_multiple: false, choose_url: false, media_library: { config: { multiple: false } }, hint: "Opsional: Gambar khusus untuk share di media sosial (ukuran ideal 1200x630px)."}
          - {label: "OG Type", name: "ogType", widget: "string", required: false, default: "article", hint: "Opsional: Tipe konten untuk Open Graph (e.g., article, website)."}
      
      - {label: "Body", name: "body", widget: "markdown", required: true, hint: "Konten utama postingan blog (Markdown)."}